[package]
name = "univ_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
select = "0.5"
rss = "2.0"